= Codename One CEF Support

This project is a preview that allows you to use CEF (Chromium Embedded Framework) in the Codename One Simulator, instead of the old JavaFX.  CEF will then be used for the BrowserComponent and AV playback.


Eventually we hope to transition entirely away from JavaFX in favor of CEF, but we start here with this preview.

== Status

. Mac OS, Windows (x86 and x86_64), and Linux (x86_64) supported

== Known issues

. No proprietary codecs (.h264) are currently supported.  This will be added soon.

== Installation

=== Mac OS

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-mac.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.


=== Windows

==== 64-bit

Run the following in bash.  I'm using git bash, but cygwin will probably work too.

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-win64.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.

==== 32-bit

Run the following in bash.  I'm using git bash, but cygwin will probably work too.

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-win32.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.


NOTE: You can install both win32 and win64.  The installer scripts will check to make sure the versions match, and will just copy the native files if cef is already installed.

=== Linux

NOTE: Currently only x86_64 architecture supported

Run the following in bash.  I'm using git bash, but cygwin will probably work too.

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-linux.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.


== Building From Source


**On Mac**

Requirements:

1. JDK8 or higher
2. ant on your PATH
3. Xcode command-line tools installed

[source,bash]
----
sh build-mac.sh
----

This will check out the a https://github.com/shannah/java-cef[java-cef fork] that we maintain for CN1 support, and build it using xcodebuild.

**On Windows**

Requirements:

1. JDK8 or higher
2. ant on your PATH
3. Visual Studio 2015 with Visual Studio C++ Tools installed
4. MSBuild 2015 installed
5. CMake version 2.8.12.2 or newer.
6. Python version 2.6+ or 3+.

[source,bash]
----
sh build-win64.sh
----

This will check out the a https://github.com/shannah/java-cef[java-cef fork] that we maintain for CN1 support, and build it.

To build for win32, first set the `$JAVA_HOME_X86` environment variable to the path to your 32-bit JDK, then run `sh build-win32.sh`.

NOTE:  If building both win64 and win32, you will need to delete the "java-cef" directory after buildingn one and before building the other.  (Or at least clear out the build files in it).

**On Linux**

Requirements:

. CMake version 2.8.12.2 or newer.
. Git.
. Java version 7 to 14.
. Python version 2.6+ or 3+.

[source,bash]
----
sh build-linux.sh
----

This will check out the a https://github.com/shannah/java-cef[java-cef fork] that we maintain for CN1 support, and build it.


== Links

. https://www.codenameone.com[Codename One Website]
. https://github.com/shannah/java-cef[The Java-CEF fork we use]
. https://github.com/chromiumembedded/java-cef[Java-CEF website]

