= Codename One CEF Support

This project is a preview that allows you to use CEF (Chromium Embedded Framework) in the Codename One Simulator, instead of the old JavaFX.  CEF will then be used for the BrowserComponent and AV playback.


Eventually we hope to transition entirely away from JavaFX in favor of CEF, but we start here with this preview.

== Status

. Mac OS, Windows (x86 and x86_64), and Linux (x86_64) supported

== Known issues

. No proprietary codecs (.h264) are currently supported.  This will be added soon.

== Installation

=== Mac OS

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-mac.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.

=== Windows

==== 64-bit

Run the following in bash.  I'm using git bash, but cygwin will probably work too.

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-win64.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.

==== 32-bit

Run the following in bash.  I'm using git bash, but cygwin will probably work too.

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-win32.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.


NOTE: You can install both win32 and win64.  The installer scripts will check to make sure the versions match, and will just copy the native files if cef is already installed.

=== Linux

NOTE: Currently only x86_64 architecture supported

Run the following in bash.  I'm using git bash, but cygwin will probably work too.

[source,bash]
----
git clone https://github.com/shannah/codenameone-cef
cd codenameone-cef
sh install-linux.sh
----

This will install CEF in ~/.codenameone/cef.   The Codename One simulator will check there the next time it runs, and will opt to use CEF instead of JavaFX if it finds it.


== Building From Source


=== On Mac

Requirements:

1. JDK8 or higher
2. ant on your PATH
3. Xcode command-line tools installed

[source,bash]
----
sh build-mac.sh
----

This will check out the a https://github.com/shannah/java-cef[java-cef fork] that we maintain for CN1 support, and build it using xcodebuild.

==== Building CEF with Proprietary Codecs

Default JCEF builds don't have proprietary codec support (e.g. h.264), so, if you need to update CEF (not JCEF, but CEF itself), you'll need to build it from source.  The `build-mac.sh` script is currently set to download a prebuilt cef binary from google drive that has been built with proprietary codec support.  The process for updating CEF is roughly as follows:

1. Follow changes in the https://github.com/chromiumembedded/java-cef/[upstream java-cef repository] to identify changes that we may wish to apply to the https://github.com/shannah/java-cef/[Codename One fork of java-cef].  Specifically, look for the `CEF_VERSION` variable in the https://github.com/chromiumembedded/java-cef/blob/master/CMakeLists.txt[CMakeLists.txt] file:
+
[source,make]
----
set(CEF_VERSION "84.3.8+gc8a556f+chromium-84.0.4147.105")
----
+
2. Follow the https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding[CEF instructions for building from source].  See "Building From Source" > "Automated Method".
+
The "update.sh" script from https://bitbucket.org/chromiumembedded/cef/wiki/MasterBuildQuickStart.md[the build instructions] should be:
+
[source,bash]
----
#!/bin/bash
export CEF_USE_GN=1
export GN_DEFINES="is_official_build=true proprietary_codecs=true ffmpeg_branding=Chrome"
python ../automate/automate-git.py --download-dir=/Users/shannah/code/chromium_git --depot-tools-dir=/Users/shannah/code/depot_tools --force-distrib --force-build --force-update --x64-build --branch=4147
----
+
The `--branch` directive in the above snippet should be the branch referenced in the `CEF_VERSION` variable of the CMakeLists.txt above.  In the example above, the branch is 4147.
3. Upload the resulting cef_binary_XXXX+chromium-XXXXX_macosx64.zip file to Google drive, and create a public link to it.
4. Update the build-mac.sh script to point to the new cef_binary that you uploaded to Google drive.
+
[source,bash]
----
FILENAME=cef_binary_84.4.1+gfdc7504+chromium-84.0.4147.105_macosx64
FILEID=1YWWJT6ng1T6LAc-zztmWs3bsUTNcjyLP
----
5. Update the java-cef/src/CMakeLists.txt file, if necessary to match the version of cef_binary that you built.
6. Run `sh build-mac.sh clean` again

=== On Windows

Requirements:

1. JDK8 or higher
2. ant on your PATH
3. Visual Studio 2015 with Visual Studio C++ Tools installed
4. MSBuild 2015 installed
5. CMake version 2.8.12.2 or newer.
6. Python version 2.6+ or 3+.

[source,bash]
----
sh build-win64.sh
----

This will check out the a https://github.com/shannah/java-cef[java-cef fork] that we maintain for CN1 support, and build it.

To build for win32, first set the `$JAVA_HOME_X86` environment variable to the path to your 32-bit JDK, then run `sh build-win32.sh`.

NOTE:  If building both win64 and win32, you will need to delete the "java-cef" directory after buildingn one and before building the other.  (Or at least clear out the build files in it).

=== On Linux

Requirements:

. CMake version 2.8.12.2 or newer.
. Git.
. Java version 7 to 14.
. Python version 2.6+ or 3+.

[source,bash]
----
sh build-linux.sh
----

This will check out the a https://github.com/shannah/java-cef[java-cef fork] that we maintain for CN1 support, and build it.

==== Building CEF with Proprietary Codecs

If you need to update CEF (not JCEF, but CEF), then you can't just use an official build because we require proprietary codec support (h.264, etc.)  To build CEF on linux, the best way that I've found is to use the https://github.com/sealemar/cef-dockerized[cef-dockerized] project which uses docker to build with all required dependencies.  

1. Checkout the repo
2. Update the cef/script/set_env.sh file so that the `GN_DEFINES` variable is:
+
[source,bash]
----
export GN_DEFINES="is_official_build=true use_sysroot=true use_allocator=none symbol_level=1 enable_nacl=false use_cups=false proprietary_codecs=true ffmpeg_branding=Chrome"
----
3. Add `--branch=4147` to the `extra_automate_args` environment variable.  Though this will be different if you need to build a different branch.
3. Run the command `cef_arch=x64 docker-compose run --rm cef`
+
This will take a while.  Probably about a day.
4. When it is finished, you will find a .7z file in the cef/output directory.  It's huge (like 8 gigs).  Extract this file.
5. After the file is finished extracting you'll find the zip archive for CEF that we can use for building jcef at `chromium_git/chromium/src/cef/binary_distrib/cef_binary_84.4.1+gfdc7504+chromium-84.0.4147.105_linux64.zip`
+
Copy this file into the `java-cef/src/third_party/cef` directory and extract it.
6. Update the `CEF_VERSION` environment variable in the build-linux.sh script to match the version in the cef_binary you just extracted.  In the example above, the version would be `cef_binary_84.4.1+gfdc7504+chromium-84.0.4147.105`.
7. Run `bash build-linux.sh`

At this point, if the build worked, you should have a new zip file with this updated build inside the dist directory.


== Links

. https://www.codenameone.com[Codename One Website]
. https://github.com/shannah/java-cef[The Java-CEF fork we use]
. https://github.com/chromiumembedded/java-cef[Java-CEF website]

